add threshold_lo_ & threshold_hi_
brucefan1983/GPUMD pull request #816
Opened 2024-12-07 06:08 UTC by Youhaojen

fix the issue "If the system has exploded, unphysical structures may be saved since no upper bound is set on the uncertainty  threshold."

**Summary**
The active learning workflow can be used with `active <interval> <has_velocity> <has_force> <threshold_lo> <threshold_hi>`

**Modification**
Rename `threshold_` to `threshold_lo_`, and add `threshold_hi`

**Others**

2024-12-08 08:53 UTC, brucefan1983 commented
Thanks for the contribution. It seems you separated changes into two pull requests? Could you complete one and delete the other?

2024-12-08 09:05 UTC, Youhaojen commented
Dear Prof. Fan,

Thanks for your reply. One is for modifying active.cu another one is for modifying activate.cuh. I’m not sure how to delete another pull request. Could you merge the two in one pull request?

Thanks

Hao-Jen You

2024-12-08 09:11 UTC, brucefan1983 commented
OK, I will take care of it. I need to study the code more carefully when I have enough time. I will contact you if I have more questions.

2024-12-15 15:29 UTC, brucefan1983 commented on src/measure/active.cu
> +  if (threshold_hi_ > uncertainty && uncertainty > threshold_lo_) {
This does not seem be correct to me.

2024-12-15 15:30 UTC, brucefan1983 commented
@elindgren Do you think it is necessary to have an upper limit?

2024-12-16 15:22 UTC, elindgren requested changes
I think it makes sense to have an upper cutoff for the use case that you describe. The high cutoff could potentially be an internal value, but it would probably be difficult to know what an appropriate value would be in general.

For readability, I would suggest renaming `threshold_lo_` to `threshold_high_` and `threshold_hi_` to `threshold_high_`, respectively.

Also, modify the documentation for the `active` keyword to reflect the new usage, including the examples. The relevant file can be found here: https://github.com/brucefan1983/GPUMD/blob/master/doc/gpumd/input_parameters/active.rst

2024-12-16 15:22 UTC, elindgren commented on src/measure/active.cu
> +    threshold_lo_, threshold_hi_,
```suggestion
    "    will check if uncertainties exceed %f and are below %f every %d iterations.\n",
    threshold_lo_, threshold_hi_,
```

2024-12-16 15:22 UTC, elindgren commented on src/measure/active.cu
> +  if (!is_valid_real(param[5], &threshold_hi_)) {
```suggestion
  if (!is_valid_real(param[4], &threshold_low_)) {
    PRINT_INPUT_ERROR("threshold_low should be a real number.\n");
  }
  if (!is_valid_real(param[5], &threshold_high_)) {
```

2024-12-16 15:22 UTC, elindgren commented on src/measure/active.cu
>      PRINT_INPUT_ERROR("threshold should be a real number.\n");
```suggestion
    PRINT_INPUT_ERROR("threshold_high should be a real number.\n");
```

2024-12-16 15:22 UTC, elindgren commented on src/measure/active.cu
> +  if (threshold_hi_ > uncertainty && uncertainty > threshold_lo_) {
```suggestion
  if (threshold_high_ > uncertainty && uncertainty > threshold_low_) {
```

2024-12-16 15:24 UTC, elindgren commented
> @elindgren Do you think it is necessary to have an upper limit?

I have not encountered this situation personally, but I can see it potentially being an issue. My main concern is if it should be set by the user, or be an internal fixed parameter. As I said in my other comment, I think it's difficult to set a good value for an internal parameter however.

2024-12-16 23:53 UTC, Youhaojen commented
@elindgren I agree. The value of the upper cutoff sometimes requires some experience to choose. However, this functionality mainly references the [exploration part of dpgen](https://docs.deepmodeling.com/projects/dpgen/en/latest/run/example-of-param.html#exploration). Therefore, I think we might be able to implement this functionality here as well.

BTW, don't forget to modify the `active.cuh` together. #817

2024-12-19 18:05 UTC, brucefan1983 commented
> @elindgren I agree. The value of the upper cutoff sometimes requires some experience to choose. However, this functionality mainly references the [exploration part of dpgen](https://docs.deepmodeling.com/projects/dpgen/en/latest/run/example-of-param.html#exploration). Therefore, I think we might be able to implement this functionality here as well.
> 
> BTW, don't forget to modify the `active.cuh` together. #817

I think you need to take care of this. We cannot merge a broken code.

2025-04-14 17:51 UTC, brucefan1983 commented
Do you still want to finishe this PR? @Youhaojen

2025-04-28 22:21 UTC, Youhaojen commented
The PR can be closed. This is not necessary for GPUMD, as the function has already been added to my active learning workflow code. The code is almost completed, and it will also support GPUMD 4.0.0. I will let you know once the code is released. Thanks. @brucefan1983

2025-04-29 08:54 UTC, brucefan1983 commented
> The PR can be closed. This is not necessary for GPUMD, as the function has already been added to my active learning workflow code. The code is almost completed, and it will also support GPUMD 4.0.0. I will let you know once the code is released. Thanks. @brucefan1983

OK, I am looking forward to your new work!

2025-04-29 08:54 UTC, closed without merging